name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Check for build and type issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

        # use astro check for issues; it needs more than Node's default heap
      - name: Run Astro check
        run: node --max-old-space-size=8192 node_modules/astro/bin/astro.mjs check

        # ensure build works
      - name: Run Astro build
        run: npm run build
